//go:build windows

package dialogues

const (
	Start           = "Your eyes adjust to the dim light, revealing a vast cavern..."
	Room            = "You are in cavern %d.\n"
	Tunnels         = "Tunnels lead to %s.\n"
	BatsNearby      = "The distant fluttering of bats reaches your ears!"
	PitsNearby      = "A chilling draft suggests the presence of a pit nearby!"
	WumpusNearby    = "An unmistakable scent hints at a Wumpus lurking nearby!"
	ChoiceShootMove = "Move or Shoot ? ( M / S ): "
	WhereTo         = "Where to ? ( %s ): "
	WhereToArrow    = "-> Aim your arrow: ( %s ): "
	NotNumber       = "This is not a number."
	NotValidDest    = "That path is blocked. Choose another direction!"
	StumbledWumpus  = "You accidentally stumbled upon the Wumpus!"
	StartledWumpus  = "Your presence spooked the Wumpus, causing it to flee!"
	KilledByWumpus0 = "☠It ate you!☠"
	KilledByWumpus1 = "The Wumpus, emerging from the shadows, made you its prey!"
	KilledByWumpus2 = "The lurking Wumpus caught you off-guard! Your adventure ends here"
	KilledByWumpus3 = "In a fateful encounter, the Wumpus proved to be your doom!"
	KilledByWumpus4 = "The Wumpus, swift and silent, ended your journey abruptly!"
	BatTeleport0    = "A giant bat took you away and dropped you into cavern %d!\n"
	BatTeleport1    = "With a flurry of wings, a giant bat snatches you up, depositing you in a new cavern %d!\n"
	BatTeleport2    = "Suddenly, talons grip you! A bat swiftly carries you aloft, dropping you in unfamiliar cavern %d.\n"
	BatTeleport3    = "The shadows move, and before you realize, a bat has whisked you away, setting you down in cavern %d. Stay alert!\n"

	FellIntoPit0    = "You lost your footing and plummeted into a bottomless pit!!"
	FellIntoPit1    = "Misstepping, you plummet into the abyss of a bottomless pit!"
	FellIntoPit2    = "The ground betrays you, sending you falling into a dark void!"
	FellIntoPit3    = "You lost your balance and met your end in the depths below!"
	MovedTo0        = "Venturing forth, you emerge in cavern %d\n"
	MovedTo1        = "Navigating the dimly lit tunnels, you find yourself in cavern %d.\n"
	MovedTo2        = "With cautious steps, you transition into the embrace of cavern %d.\n"
	MovedTo3        = "The winding paths lead you onward to the heart of cavern %d.\n"
	MovedTo4        = "A gentle echo announces your arrival in cavern %d.\n"
	MovedTo5        = "The path unfolds before you, revealing the secrets of cavern %d.\n"
	MovedTo6        = "Pushing forth, the mysteries of cavern %d lay before you.\n"
	MovedTo7        = "The tunnel's end opens up to the expanse of cavern %d.\n"
	MovedTo8        = "With each step, the ambiance changes, signaling your entry into cavern %d.\n"
	MovedTo9        = "Leaving the familiar behind, you're greeted by the sights and sounds of cavern %d.\n"
	MovedTo10       = "As the previous chamber fades, the allure of cavern %d beckons.\n"
	PlayAGain       = "Would you like to venture again into the unknown? (Y/N):"
	DontUnderstand  = "I'm sorry I couldn't quite catch that..."
	FireArrow       = "You fired a curved arrow ->"
	SelectPower     = "How far into the caverns will you let the arrow fly? (1-5):"
	ArrowTravel     = "➵ The arrow arcs gracefully, eventually reaching cavern %d.\n"
	KilledWumpus0   = "-> With a triumphant strike, your arrow fells the Wumpus! Victory is yours!"
	KilledWumpus1   = "-> With a resounding impact, your arrow finds its mark! The Wumpus falls defeated! Victory is yours!"
	KilledWumpus2   = "-> As the echo of the arrow's flight fades, the Wumpus lets out a final cry! You've vanquished the beast!"
	KilledWumpus3   = "-> Your aim is true, and the Wumpus is no more! Triumph awaits you!"
	KilledWumpus4   = "-> Against all odds, you've bested the Wumpus with a single shot! Celebrate your prowess!"
	KilledWumpus5   = "-> The caverns fall silent as the Wumpus meets its end by your arrow! Well done, adventurer!"
	ArrowStartle    = "-> The curved arrow struck the ground, startling the Wumpus !"
	ArrowFell       = "-> The arrow loses its momentum, falling harmlessly to the cavern floor."
	ArrowPlayer     = "-> A miscalculation! Your own arrow returns to strike you down!"
	WumpusTrample   = "In its panic, the Wumpus rampages through, trampling you in the process!"
	Turns           = "You won in %d turns, firing %d arrows and visiting %d caverns.\n"
	Exit0           = "As you retreat from the echoing depths of the caverns, a serene silence envelops you. Thank you for venturing into the unknown with us. Until our paths cross again in the shadows... Farewell, brave adventurer."
	Exit1           = "Your hunt for the Wumpus concludes, for now. Till we meet in the caverns again."
	Exit2           = "The Wumpus remains elusive as you depart. Until another quest calls you back."
	Exit3           = "You choose to leave the caverns, but the Wumpus awaits your return. Farewell for now."
	ExitWumpus      = "The Wumpus was hidden in cavern %d\n"
	NoMoreArrows    = "-> You don't have any arrows left !"
	RemainingArrows = "-> You have %d remaining arrows.\n"
)

// advanced features.
const (
	FirstDoorDiscoveryNoKey0 = "In a dimly lit alcove, you stumble upon a door unlike any other, its very presence an enigma. Its locked nature piques your curiosity, urging you to search for a way to access its other side."
	FirstDoorDiscoveryNoKey1 = "As you navigate the winding paths of the cavern, an imposing door with intricate engravings stands before you, sealing away its secrets. Without a key, you wonder how to unlock its mysteries."
	FirstDoorDiscoveryNoKey2 = "Amidst the shadows, the silhouette of a grand door looms. Adorned with symbols from an age long past, it poses a silent challenge: Find the key, unveil its secrets."
	FirstDoorDiscoveryNoKey3 = "The rhythmic echo of your footsteps halts abruptly as you face an ornate door, an obvious relic from ancient times. You're met with a locked barrier, urging you to find its corresponding key."
	FirstDoorDiscoveryNoKey4 = "As you traverse deeper into the labyrinth, a mysterious door stands sentinel, its purpose unknown. You ponder the whereabouts of the key that might unlock its story."
	BackAgainDoorNoKey0      = "Wandering through the labyrinth, you find yourself back at the mysterious door that had captivated your curiosity earlier. Its silent presence taunts you, and the absence of a key keeps its secrets just out of reach."
	BackAgainDoorNoKey1      = "The familiar patterns of the grand door greet you as you navigate the winding paths. A pang of frustration hits; despite your exploration, the key remains a missing piece in this puzzle."
	BackAgainDoorNoKey2      = "Once again, the cavern leads you to the ornate door you'd encountered before. It stands stoically, waiting for its key, a testament to the mysteries yet undiscovered in this maze."
	BackAgainDoorNoKey3      = "The twists and turns of the cavern converge back to the imposing door you'd stumbled upon earlier. The weight of its locked state is palpable, and the elusive key continues to be a beacon of challenge."
	BackAgainDoorNoKey4      = "You circle back to the enigmatic door that once held your gaze. Its secrets remain locked behind its grand facade, and without the key, it stands as a monument to the adventure yet to be unraveled."
	FirstKeyDiscoveryNoDoor0 = "Tucked away in a crevice, a mysterious key gleams faintly. Intrigued, you reach out, securing the key and pondering its potential use."
	FirstKeyDiscoveryNoDoor1 = "Hidden among the stones, an intricate key captures your gaze. Curiosity piqued, you carefully pick it up, wondering about its origins."
	FirstKeyDiscoveryNoDoor2 = "As you traverse the cavern, you stumble upon an enigmatic key with elaborate engravings. Without hesitation, you take it, sensing its significance."
	FirstKeyDiscoveryNoDoor3 = "In a dimly lit nook, a peculiar key with a lustrous sheen awaits. Compelled by its mystique, you decide to claim it for your journey ahead."
	FirstKeyDiscoveryNoDoor4 = "Amongst the relics of the cavern, an ornate key stands out, beckoning to be taken. You grasp it, feeling its cool weight and unspoken promise."
	FirstKeyDiscoveryNoDoor5 = "You come across an arcane key, its craftsmanship suggesting age and purpose. Drawn to its mystery, you take it, hoping it'll unlock secrets later on."
	DoorThenKey0             = "You're instantly reminded of the door's enigmatic aura when you discover a key bearing similar motifs. Convinced it's more than mere coincidence, you take the key, eager to see if it unlocks the previous mystery."
	DoorThenKey1             = "Tucked away in a corner, a key of intricate design beckons. The mysterious door from earlier springs to mind. Could this be its counterpart? With a mix of hope and curiosity, you decide to claim the key."
	DoorThenKey2             = "As you explore, a peculiar key catches your eye, and your mind drifts to the locked door you had come across. Perhaps this key could be the gateway? With anticipation, you take it with you."
	DoorThenKey3             = "The memory of that sealed door flashes back as you stumble upon a key with ancient symbols. Intrigued and optimistic, you secure the key, wondering if it might be the answer to the door's riddle."
	DoorThenKey4             = "Earlier, the sight of that imposing, locked door had puzzled you. Now, as you hold a mysterious, ornate key that you've just found, hope flickers. Could this be its match? You take the key, eager to find out."
	DoorThenKey5             = "Recalling the enigmatic door you encountered earlier, a sense of purpose fills you as you discover a beautifully crafted key hidden in the shadows. Without a second thought, you pocket it, hoping it might reveal the door's secrets."
	KeyThenDoor0             = "The ornate key you found earlier feels heavy in your pocket as you face a magnificent door, its designs eerily similar. An air of destiny surrounds you, hinting that the key might unveil the door's concealed world."
	KeyThenDoor1             = "Your fingers instinctively clutch the mysterious key you discovered earlier as you come upon an imposing door. The designs mirror each other, suggesting they're intrinsically linked. It's time to see if the key fits."
	KeyThenDoor2             = "As a grand door with ancient motifs presents itself, memories of the key you picked up flood back. The connection seems unmistakable. With anticipation, you approach, ready to test your earlier find."
	KeyThenDoor3             = "Before you stands a door, cloaked in mystery and echoing tales of old. The key you'd stumbled upon earlier now feels purposeful, as if it's the missing piece of this puzzle."
	KeyThenDoor4             = "The sight of the enigmatic door reminds you of the key you found. With symbols and engravings that seem to tell of a shared history, you can't help but wonder if the key might unlock the door's secrets."
	WumpusStillAlive0        = "However, a sense of duty holds you back. The echoing growls of the Wumpus are a reminder that your quest is not yet complete."
	WumpusStillAlive1        = "Yet, as you stand at the threshold, you realize your mission remains unfinished. The Wumpus still lurks, and you cannot leave it unchecked."
	WumpusStillAlive2        = "But a lingering unease prevents your exit. The Wumpus, that menacing beast, still roams the labyrinth. Your job isn't done."
	WumpusStillAlive3        = "Although freedom beckons, a nagging thought anchors you. The Wumpus is still at large, and you're not one to leave a task half-done."
	WumpusStillAlive4        = "But you resist the call of the outside world. Somewhere in the shadows, the Wumpus waits, and you're determined to confront it."
	DoorKeyDoor0             = "Returning to the cavern that houses the mysterious door, you feel the weight of the key you've since discovered. Anticipation grows as you approach, ready to unlock the door's long-held secrets."
	DoorKeyDoor1             = "The winding paths of the labyrinth lead you back to the grand door. With the newly acquired key in hand, the moment feels ripe to finally reveal what lies beyond its imposing facade."
	DoorKeyDoor2             = "With the ornate key you found, you trace your steps back to the enigmatic door that once stood as an inscrutable barrier. A sense of destiny fills the air as you inch closer to unveiling its mysteries."
	DoorKeyDoor3             = "The familiar designs of the door beckon as you navigate the cavern once more. The key, now in your possession, promises to shed light on the door's hidden tales."
	DoorKeyDoor4             = "Back in the chamber where the intricate door first captured your wonder, the key you've discovered feels like the final piece of this puzzle. The anticipation is palpable as you prepare to turn it, bridging the gap between mystery and revelation."
	ExitDoor0                = "With a deep breath, you turn the key and the door gradually gives way, leading you to the world outside the maze."
	ExitDoor1                = "Holding the key, a moment of clarity strikes. With a swift motion, you unlock the door, and it swings open to display the vast expanse outside the maze."
	ExitDoor2                = "The intricate design of the key glints under the dim light. Turning it, the door eases open, showing the boundless horizon beyond the labyrinth."
	ExitDoor3                = "With the key's cold metal pressed against your fingers, anticipation mounts. Unlocking the door, it opens up to the freedom of the world outside."
	NowExit                  = "Trapped within these winding walls, you must seek an exit."
	MaybeDoor                = "Could the enigmatic door you stumbled upon be your passage out?"
	MaybeKey                 = "The ornate key you discovered might hold answers to this labyrinth's riddles."
	CertainKeyDoor           = "The door for which you have the key calls to you. It's time to retrace your steps and make your way to the surface through that passage!"
)
