//go:build windows

package dialogues

const (
	Start           = "Your eyes adjust to the dim light, revealing a vast cavern..."
	Room            = "You are in cavern %d.\n"
	Tunnels         = "Tunnels lead to %s.\n"
	BatsNearby      = "The distant fluttering of bats reaches your ears!"
	PitsNearby      = "A chilling draft suggests the presence of a pit nearby!"
	WumpusNearby    = "An unmistakable scent hints at a Wumpus lurking nearby!"
	ChoiceShootMove = "Move or Shoot ? ( M / S ): "
	WhereTo         = "Where to ? ( %s ): "
	WhereToArrow    = "-> Aim your arrow: ( %s ): "
	NotNumber       = "This is not a number."
	NotValidDest    = "That path is blocked. Choose another direction!"
	StumbledWumpus  = "You accidentally stumbled upon the Wumpus!"
	StartledWumpus  = "Your presence spooked the Wumpus, causing it to flee!"
	KilledByWumpus0 = "☠It ate you!☠"
	KilledByWumpus1 = "The Wumpus, emerging from the shadows, made you its prey!"
	KilledByWumpus2 = "The lurking Wumpus caught you off-guard! Your adventure ends here"
	KilledByWumpus3 = "In a fateful encounter, the Wumpus proved to be your doom!"
	KilledByWumpus4 = "The Wumpus, swift and silent, ended your journey abruptly!"
	BatTeleport     = "A giant bat took you away and dropped you into cavern %d!\n"
	FellIntoPit0    = "You lost your footing and plummeted into a bottomless pit!!"
	FellIntoPit1    = "Misstepping, you plummet into the abyss of a bottomless pit!"
	FellIntoPit2    = "The ground betrays you, sending you falling into a dark void!"
	FellIntoPit3    = "You lost your balance and met your end in the depths below!"
	MovedTo0        = "Venturing forth, you emerge in cavern %d\n"
	MovedTo1        = "Navigating the dimly lit tunnels, you find yourself in cavern %d.\n"
	MovedTo2        = "With cautious steps, you transition into the embrace of cavern %d.\n"
	MovedTo3        = "The winding paths lead you onward to the heart of cavern %d.\n"
	MovedTo4        = "A gentle echo announces your arrival in cavern %d.\n"
	MovedTo5        = "The path unfolds before you, revealing the secrets of cavern %d.\n"
	MovedTo6        = "Pushing forth, the mysteries of cavern %d lay before you.\n"
	MovedTo7        = "The tunnel's end opens up to the expanse of cavern %d.\n"
	MovedTo8        = "With each step, the ambiance changes, signaling your entry into cavern %d.\n"
	MovedTo9        = "Leaving the familiar behind, you're greeted by the sights and sounds of cavern %d.\n"
	MovedTo10       = "As the previous chamber fades, the allure of cavern %d beckons.\n"
	PlayAGain       = "Would you like to venture again into the unknown? (Y/N):"
	DontUnderstand  = "I'm sorry I couldn't quite catch that..."
	FireArrow       = "You fired a curved arrow ->"
	SelectPower     = "How far into the caverns will you let the arrow fly? (1-5):"
	ArrowTravel     = "➵ The arrow arcs gracefully, eventually reaching cavern %d.\n"
	KilledWumpus0   = "-> With a triumphant strike, your arrow fells the Wumpus! Victory is yours!"
	KilledWumpus1   = "-> With a resounding impact, your arrow finds its mark! The Wumpus falls defeated! Victory is yours!"
	KilledWumpus2   = "-> As the echo of the arrow's flight fades, the Wumpus lets out a final cry! You've vanquished the beast!"
	KilledWumpus3   = "-> Your aim is true, and the Wumpus is no more! Triumph awaits you!"
	KilledWumpus4   = "-> Against all odds, you've bested the Wumpus with a single shot! Celebrate your prowess!"
	KilledWumpus5   = "-> The caverns fall silent as the Wumpus meets its end by your arrow! Well done, adventurer!"
	ArrowStartle    = "-> The curved arrow struck the ground, startling the Wumpus !"
	ArrowFell       = "-> The arrow loses its momentum, falling harmlessly to the cavern floor."
	ArrowPlayer     = "-> A miscalculation! Your own arrow returns to strike you down!"
	WumpusTrample   = "In its panic, the Wumpus rampages through, trampling you in the process!"
	Turns           = "You won in %d turns, firing %d arrows and visiting %d caverns.\n"
	Exit            = "As you retreat from the echoing depths of the caverns, a serene silence envelops you. Thank you for venturing into the unknown with us. Until our paths cross again in the shadows... Farewell, brave adventurer."
	ExitWumpus      = "The Wumpus was hidden in cavern %d\n"
	NoMoreArrows    = "-> You don't have any arrows left !"
	RemainingArrows = "-> You have %d remaining arrows.\n"
)
